version: '2'
services:
  postgres:
    container_name: beerandcoffee
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=beerandcoffee
      - POSTGRES_USER=beerandcoffee
      - POSTGRES_PASSWORD=12345678
      - MAX_CONNECTIONS=300